"""add cognitive dimensions to learning_profile

Revision ID: 45617e5e0796
Revises: 582c8e56edb3
Create Date: 2026-02-28 11:40:27.387943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45617e5e0796'
down_revision: Union[str, Sequence[str], None] = '582c8e56edb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_profiles', sa.Column('analogy_score', sa.Float(), nullable=True))
    op.add_column('learning_profiles', sa.Column('practical_thinking_score', sa.Float(), nullable=True))
    op.add_column('learning_profiles', sa.Column('narrative_style_score', sa.Float(), nullable=True))
    op.add_column('learning_profiles', sa.Column('abstract_depth_score', sa.Float(), nullable=True))
    op.add_column('learning_profiles', sa.Column('total_analyses', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_profiles', 'total_analyses')
    op.drop_column('learning_profiles', 'abstract_depth_score')
    op.drop_column('learning_profiles', 'narrative_style_score')
    op.drop_column('learning_profiles', 'practical_thinking_score')
    op.drop_column('learning_profiles', 'analogy_score')
    # ### end Alembic commands ###
